name: Update Profile View Counter

on:
  workflow_dispatch:
  page_build:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read current counter
      id: read_counter
      run: echo "::set-output name=current::$(cat counter.txt)"

    - name: Increment counter
      id: increment_counter
      run: echo $(( ${{ steps.read_counter.outputs.current }} + 1 )) > counter.txt

    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add counter.txt
        git commit -m "Increment profile view counter"
        git push https://${GH_TOKEN}@github.com/tugrulsubekci/tugrulsubekci.git HEAD:main
